export const table = [
  {
    user: "John Doe",
    category: "Congés payés",
    period: "2020-2021",
    currentBalance: 1600,
    balanceTaken: 2500,
    futureBalance: 3400,
  },
  {
    user: "Jane Smith",
    category: "Congés payés",
    period: "2021-2022",
    currentBalance: 2000,
    balanceTaken: 150,
    futureBalance: 2500,
  },
  {
    user: "Alice Johnson",
    category: "Congés payés",
    period: "2022-2023",
    currentBalance: 180,
    balanceTaken: 2000,
    futureBalance: 280,
  },
  {
    user: "Bob Williams",
    category: "Congés payés",
    period: "2023-2024",
    currentBalance: 225,
    balanceTaken: 185,
    futureBalance: 3000,
  },
  {
    user: "Emily Davis",
    category: "Congés payés",
    period: "2024-2025",
    currentBalance: 156,
    balanceTaken: 2259,
    futureBalance: 2545,
  },
  {
    user: "Michael Brown",
    category: "Congés payés",
    period: "2025-2026",
    currentBalance: 1912,
    balanceTaken: 1643,
    futureBalance: 2334,
  },
  // {
  //   user: "Olivia Wilson",
  //   category: "Congés payés",
  //   period: "2026-2027",
  //   currentBalance: 17,
  //   balanceTaken: 19,
  //   futureBalance: 26,
  // },
  // {
  //   user: "William Taylor",
  //   category: "Congés payés",
  //   period: "2027-2028",
  //   currentBalance: 21,
  //   balanceTaken: 17,
  //   futureBalance: 29,
  // },
  // {
  //   user: "Sophia Martinez",
  //   category: "Congés payés",
  //   period: "2028-2029",
  //   currentBalance: 14,
  //   balanceTaken: 24,
  //   futureBalance: 31,
  // },
];
