export const table = [
  {
    user: "John Doe",
    category: "Congés payés",
    period: "2020-2021",
    currentBalance: 16,
    balanceTaken: 25,
    futureBalance: 34,
  },
  {
    user: "Jane Smith",
    category: "Congés payés",
    period: "2021-2022",
    currentBalance: 20,
    balanceTaken: 15,
    futureBalance: 25,
  },
  {
    user: "Alice Johnson",
    category: "Congés payés",
    period: "2022-2023",
    currentBalance: 18,
    balanceTaken: 20,
    futureBalance: 28,
  },
  {
    user: "Bob Williams",
    category: "Congés payés",
    period: "2023-2024",
    currentBalance: 22,
    balanceTaken: 18,
    futureBalance: 30,
  },
  {
    user: "Emily Davis",
    category: "Congés payés",
    period: "2024-2025",
    currentBalance: 15,
    balanceTaken: 22,
    futureBalance: 25,
  },
  {
    user: "Michael Brown",
    category: "Congés payés",
    period: "2025-2026",
    currentBalance: 19,
    balanceTaken: 16,
    futureBalance: 23,
  },
  {
    user: "Olivia Wilson",
    category: "Congés payés",
    period: "2026-2027",
    currentBalance: 17,
    balanceTaken: 19,
    futureBalance: 26,
  },
  {
    user: "William Taylor",
    category: "Congés payés",
    period: "2027-2028",
    currentBalance: 21,
    balanceTaken: 17,
    futureBalance: 29,
  },
  {
    user: "Sophia Martinez",
    category: "Congés payés",
    period: "2028-2029",
    currentBalance: 14,
    balanceTaken: 24,
    futureBalance: 31,
  },
];
